### ISSUE TITLE
same argument for o1 and o2

### ISSUE THREAD

**Issue by punitvara** [troglobit/ntpclient#1]
In rate.awk `FNR` is used to read only one record. `o1` and `o2` has same argument `$5`.For same record argument will be the same .slop is using calculation `o1` subtracting from `o2` .It will be always zero.

**Comment by troglobit** [comment]
Do you have a proposed fix?  Otherwise I might just delete the script instead (since I don't use it, only kept it for compat with Larry's version).

**Comment by punitvara** [comment]
I do not have any proposed fix right now. But I am trying to find some solution . I have forked your repo . So you can delete the file.

**Comment by troglobit** [comment]
I'll await your pull request then, or any further comments here before I do anything.
Thanks for looking into this! :+1:

**Comment by punitvara** [comment]
Your welcome :+1:

**Comment by troglobit** [comment]
No action for 1½ years, closing ...
