### ISSUE TITLE
Use IPV4 if IPV6 is present and disabled.

### ISSUE THREAD

**Issue by tur-tle** [troglobit/ntpclient#2]
When booting a Linux system with the kernel command line option:
 ipv6.disable=1 the IPV6 kernel module will be loaded but administratively disabled. 
If I try to use ntpclient 2017.246 on such a system to set the time and exit:
 ntpclient -dstvn pool.ntp.org
I get
ERROR - Failed creating UDP socket() to SNTP server: Address family not supported by protocol
Booting without this option eliminates the issue.

**Comment by troglobit** [comment]
Ah, good catch!  The intention was to add fail-over support to create the socket with `socket(AF_INET, ...)` if `AF_INET6` is missing.  Care to take a stab at it and whip up a patch/pull-request?

**Comment by tur-tle** [comment]
Yeah okay.
Thank you for the fast response.

**Comment by wmyrda** [comment]
I have run into same problem except on my system there was no ipv6 at all as it was disabled in the kernel config not during boot (grub, sysctl etc.)

**Comment by troglobit** [comment]
No follow-up yet from @tur-tle on this, maybe you can take a look at the IPv4 fail-over support, @wmyrda ?

**Comment by wmyrda** [comment]
@troglobit As I am not a programmer the best I could do is take a look which commit broke things, but I wish someone else stepped up and did it as I am now heavily involved in other projects as `adblock2privoxy`

**Comment by troglobit** [comment]
@wmyrda No worries, I'll put it on my own backlog. We already know which commit that broke your use-case, it added IPv6 support, so reverting that is not a solution.

**Comment by troglobit** [comment]
Turned out to be a simple fix. I'll see what I can do about pushing out a new release in the coming week, but I'll be traveling so can't make any promises.

Thanks for reporting this!

**Comment by wmyrda** [comment]
WOW You mean to say you wrote that in like 15min?? 
Great job!

**Comment by troglobit** [comment]
@wmyrda Took longer to find a system setup to reproduce the problem ;-)

**Comment by troglobit** [comment]
There, [v2018_176 released](/troglobit/ntpclient/releases/2018_176) now :-)
